CREATE TABLE IF NOT EXISTS user (
  pk INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  id TEXT NOT NULL UNIQUE,
  username TEXT NOT NULL UNIQUE,
  password TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS actor (
    pk INTEGER PRIMARY KEY AUTOINCREMENT,
    id TEXT NOT NULL UNIQUE,
    type TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS chat (
    pk INTEGER PRIMARY KEY AUTOINCREMENT,
    id TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS chat_actor (
    pk INTEGER PRIMARY KEY AUTOINCREMENT,
    chat_id TEXT NOT NULL,
    actor_id TEXT NOT NULL,
    FOREIGN KEY (chat_id) REFERENCES chat(id),
    FOREIGN KEY (actor_id) REFERENCES actor(id)
);

CREATE TABLE IF NOT EXISTS message (
    pk INTEGER PRIMARY KEY AUTOINCREMENT,
    id TEXT NOT NULL UNIQUE,
    chat_id TEXT NOT NULL,
    actor_id TEXT NOT NULL,
    text TEXT NOT NULL,
    -- created_at TEXT NOT NULL,
    FOREIGN KEY (chat_id) REFERENCES chat(id),
    FOREIGN KEY (actor_id) REFERENCES actor(id)
);
